/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import java.util.*;
import nada.analysis.*;

@SuppressWarnings("nls")
public final class ADeclPart extends PDeclPart
{
    private final LinkedList<PBasicDecl> _basicDecl_ = new LinkedList<PBasicDecl>();

    public ADeclPart()
    {
        // Constructor
    }

    public ADeclPart(
        @SuppressWarnings("hiding") List<?> _basicDecl_)
    {
        // Constructor
        setBasicDecl(_basicDecl_);

    }

    @Override
    public Object clone()
    {
        return new ADeclPart(
            cloneList(this._basicDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclPart(this);
    }

    public LinkedList<PBasicDecl> getBasicDecl()
    {
        return this._basicDecl_;
    }

    public void setBasicDecl(List<?> list)
    {
        for(PBasicDecl e : this._basicDecl_)
        {
            e.parent(null);
        }
        this._basicDecl_.clear();

        for(Object obj_e : list)
        {
            PBasicDecl e = (PBasicDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._basicDecl_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._basicDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._basicDecl_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PBasicDecl> i = this._basicDecl_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PBasicDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
