/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class AGeRelOp extends PRelOp
{
    private TGe _ge_;

    public AGeRelOp()
    {
        // Constructor
    }

    public AGeRelOp(
        @SuppressWarnings("hiding") TGe _ge_)
    {
        // Constructor
        setGe(_ge_);

    }

    @Override
    public Object clone()
    {
        return new AGeRelOp(
            cloneNode(this._ge_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGeRelOp(this);
    }

    public TGe getGe()
    {
        return this._ge_;
    }

    public void setGe(TGe node)
    {
        if(this._ge_ != null)
        {
            this._ge_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ge_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ge_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ge_ == child)
        {
            this._ge_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ge_ == oldChild)
        {
            setGe((TGe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
