/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class ANada extends PNada
{
    private PSubprogramBody _subprogramBody_;

    public ANada()
    {
        // Constructor
    }

    public ANada(
        @SuppressWarnings("hiding") PSubprogramBody _subprogramBody_)
    {
        // Constructor
        setSubprogramBody(_subprogramBody_);

    }

    @Override
    public Object clone()
    {
        return new ANada(
            cloneNode(this._subprogramBody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANada(this);
    }

    public PSubprogramBody getSubprogramBody()
    {
        return this._subprogramBody_;
    }

    public void setSubprogramBody(PSubprogramBody node)
    {
        if(this._subprogramBody_ != null)
        {
            this._subprogramBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subprogramBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subprogramBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subprogramBody_ == child)
        {
            this._subprogramBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subprogramBody_ == oldChild)
        {
            setSubprogramBody((PSubprogramBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
