/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class ANegPrimFactor extends PFactor
{
    private TMinus _minus_;
    private PPrimary _primary_;

    public ANegPrimFactor()
    {
        // Constructor
    }

    public ANegPrimFactor(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PPrimary _primary_)
    {
        // Constructor
        setMinus(_minus_);

        setPrimary(_primary_);

    }

    @Override
    public Object clone()
    {
        return new ANegPrimFactor(
            cloneNode(this._minus_),
            cloneNode(this._primary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegPrimFactor(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PPrimary getPrimary()
    {
        return this._primary_;
    }

    public void setPrimary(PPrimary node)
    {
        if(this._primary_ != null)
        {
            this._primary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._primary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._primary_ == child)
        {
            this._primary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._primary_ == oldChild)
        {
            setPrimary((PPrimary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
