/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class ANullStmtSimpleStmt extends PSimpleStmt
{
    private PNullStmt _nullStmt_;

    public ANullStmtSimpleStmt()
    {
        // Constructor
    }

    public ANullStmtSimpleStmt(
        @SuppressWarnings("hiding") PNullStmt _nullStmt_)
    {
        // Constructor
        setNullStmt(_nullStmt_);

    }

    @Override
    public Object clone()
    {
        return new ANullStmtSimpleStmt(
            cloneNode(this._nullStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANullStmtSimpleStmt(this);
    }

    public PNullStmt getNullStmt()
    {
        return this._nullStmt_;
    }

    public void setNullStmt(PNullStmt node)
    {
        if(this._nullStmt_ != null)
        {
            this._nullStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nullStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nullStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nullStmt_ == child)
        {
            this._nullStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nullStmt_ == oldChild)
        {
            setNullStmt((PNullStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
