/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class ANumDeclBasicDecl extends PBasicDecl
{
    private PNumberDecl _numberDecl_;

    public ANumDeclBasicDecl()
    {
        // Constructor
    }

    public ANumDeclBasicDecl(
        @SuppressWarnings("hiding") PNumberDecl _numberDecl_)
    {
        // Constructor
        setNumberDecl(_numberDecl_);

    }

    @Override
    public Object clone()
    {
        return new ANumDeclBasicDecl(
            cloneNode(this._numberDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumDeclBasicDecl(this);
    }

    public PNumberDecl getNumberDecl()
    {
        return this._numberDecl_;
    }

    public void setNumberDecl(PNumberDecl node)
    {
        if(this._numberDecl_ != null)
        {
            this._numberDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numberDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numberDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numberDecl_ == child)
        {
            this._numberDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numberDecl_ == oldChild)
        {
            setNumberDecl((PNumberDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
