/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class ANumLitPrimary extends PPrimary
{
    private TNumberLit _numberLit_;

    public ANumLitPrimary()
    {
        // Constructor
    }

    public ANumLitPrimary(
        @SuppressWarnings("hiding") TNumberLit _numberLit_)
    {
        // Constructor
        setNumberLit(_numberLit_);

    }

    @Override
    public Object clone()
    {
        return new ANumLitPrimary(
            cloneNode(this._numberLit_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumLitPrimary(this);
    }

    public TNumberLit getNumberLit()
    {
        return this._numberLit_;
    }

    public void setNumberLit(TNumberLit node)
    {
        if(this._numberLit_ != null)
        {
            this._numberLit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numberLit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numberLit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numberLit_ == child)
        {
            this._numberLit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numberLit_ == oldChild)
        {
            setNumberLit((TNumberLit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
