/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class AObjDeclBasicDecl extends PBasicDecl
{
    private PObjectDecl _objectDecl_;

    public AObjDeclBasicDecl()
    {
        // Constructor
    }

    public AObjDeclBasicDecl(
        @SuppressWarnings("hiding") PObjectDecl _objectDecl_)
    {
        // Constructor
        setObjectDecl(_objectDecl_);

    }

    @Override
    public Object clone()
    {
        return new AObjDeclBasicDecl(
            cloneNode(this._objectDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjDeclBasicDecl(this);
    }

    public PObjectDecl getObjectDecl()
    {
        return this._objectDecl_;
    }

    public void setObjectDecl(PObjectDecl node)
    {
        if(this._objectDecl_ != null)
        {
            this._objectDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objectDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objectDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objectDecl_ == child)
        {
            this._objectDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objectDecl_ == oldChild)
        {
            setObjectDecl((PObjectDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
