/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class AProcCallStmt extends PProcCallStmt
{
    private TIdent _ident_;
    private PActualParamPart _actualParamPart_;
    private TSemi _semi_;

    public AProcCallStmt()
    {
        // Constructor
    }

    public AProcCallStmt(
        @SuppressWarnings("hiding") TIdent _ident_,
        @SuppressWarnings("hiding") PActualParamPart _actualParamPart_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setIdent(_ident_);

        setActualParamPart(_actualParamPart_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AProcCallStmt(
            cloneNode(this._ident_),
            cloneNode(this._actualParamPart_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcCallStmt(this);
    }

    public TIdent getIdent()
    {
        return this._ident_;
    }

    public void setIdent(TIdent node)
    {
        if(this._ident_ != null)
        {
            this._ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ident_ = node;
    }

    public PActualParamPart getActualParamPart()
    {
        return this._actualParamPart_;
    }

    public void setActualParamPart(PActualParamPart node)
    {
        if(this._actualParamPart_ != null)
        {
            this._actualParamPart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualParamPart_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ident_)
            + toString(this._actualParamPart_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ident_ == child)
        {
            this._ident_ = null;
            return;
        }

        if(this._actualParamPart_ == child)
        {
            this._actualParamPart_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        if(this._actualParamPart_ == oldChild)
        {
            setActualParamPart((PActualParamPart) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
