/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class AProcCallStmtSimpleStmt extends PSimpleStmt
{
    private PProcCallStmt _procCallStmt_;

    public AProcCallStmtSimpleStmt()
    {
        // Constructor
    }

    public AProcCallStmtSimpleStmt(
        @SuppressWarnings("hiding") PProcCallStmt _procCallStmt_)
    {
        // Constructor
        setProcCallStmt(_procCallStmt_);

    }

    @Override
    public Object clone()
    {
        return new AProcCallStmtSimpleStmt(
            cloneNode(this._procCallStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcCallStmtSimpleStmt(this);
    }

    public PProcCallStmt getProcCallStmt()
    {
        return this._procCallStmt_;
    }

    public void setProcCallStmt(PProcCallStmt node)
    {
        if(this._procCallStmt_ != null)
        {
            this._procCallStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._procCallStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._procCallStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._procCallStmt_ == child)
        {
            this._procCallStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._procCallStmt_ == oldChild)
        {
            setProcCallStmt((PProcCallStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
