/* This file was generated by SableCC (http://www.sablecc.org/). */

package nada.node;

import nada.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExprWriteExpr extends PWriteExpr
{
    private PSimpleExpr _simpleExpr_;

    public ASimpleExprWriteExpr()
    {
        // Constructor
    }

    public ASimpleExprWriteExpr(
        @SuppressWarnings("hiding") PSimpleExpr _simpleExpr_)
    {
        // Constructor
        setSimpleExpr(_simpleExpr_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExprWriteExpr(
            cloneNode(this._simpleExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExprWriteExpr(this);
    }

    public PSimpleExpr getSimpleExpr()
    {
        return this._simpleExpr_;
    }

    public void setSimpleExpr(PSimpleExpr node)
    {
        if(this._simpleExpr_ != null)
        {
            this._simpleExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleExpr_ == child)
        {
            this._simpleExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleExpr_ == oldChild)
        {
            setSimpleExpr((PSimpleExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
